import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
};

export default function TermsOfServicePage() {
  return (
    <div className="flex-1 bg-white py-6 px-4">
      <article className="w-full">
        <h1 className="mb-1 text-[13px] font-black text-gray-900 uppercase tracking-[0.25em]">
          Terms of Service
        </h1>
        <p className="mb-6 text-[10px] font-bold text-gray-400 uppercase tracking-[0.12em]">
          Version 1.0 &mdash; Last updated: February 21, 2026
        </p>

        <section className="mb-5">
          <h2 className="mb-2 text-[11px] font-black text-gray-800 uppercase tracking-[0.15em]">
            Service Description
          </h2>
          <p className="text-[11px] font-bold text-gray-500 leading-relaxed">
            This service provides AI-guided wellness and relaxation experiences.
            It is designed for adult relaxation and well-being purposes only.
            This service is <strong>not</strong> a therapy service, medical
            service, or substitute for professional mental health care.
          </p>
        </section>

        <section className="mb-5">
          <h2 className="mb-2 text-[11px] font-black text-gray-800 uppercase tracking-[0.15em]">
            Eligibility
          </h2>
          <p className="text-[11px] font-bold text-gray-500 leading-relaxed">
            You must be 18 years of age or older to use this service. By
            creating an account and completing age verification, you confirm that
            you meet this eligibility requirement.
          </p>
        </section>

        <section className="mb-5">
          <h2 className="mb-2 text-[11px] font-black text-gray-800 uppercase tracking-[0.15em]">
            AI Disclosure
          </h2>
          <p className="text-[11px] font-bold text-gray-500 leading-relaxed">
            All guidance provided through this service is generated by
            artificial intelligence. You are interacting with an AI system, not a
            human therapist, counselor, or healthcare provider. The AI-generated
            content is for wellness and relaxation purposes only.
          </p>
        </section>

        <section className="mb-5">
          <h2 className="mb-2 text-[11px] font-black text-gray-800 uppercase tracking-[0.15em]">
            Acceptable Use
          </h2>
          <p className="mb-2 text-[11px] font-bold text-gray-500 leading-relaxed">
            This service is intended for wellness and relaxation use only. You
            agree not to:
          </p>
          <ul className="ml-4 list-disc space-y-0.5 text-[11px] font-bold text-gray-500 leading-relaxed">
            <li>Use the service for any illegal purpose</li>
            <li>
              Attempt to generate content outside the scope of wellness and
              relaxation
            </li>
            <li>Misrepresent your age or identity</li>
            <li>
              Share, record, or redistribute session content without
              authorization
            </li>
          </ul>
        </section>

        <section className="mb-5">
          <h2 className="mb-2 text-[11px] font-black text-gray-800 uppercase tracking-[0.15em]">
            Content Disclaimer
          </h2>
          <p className="text-[11px] font-bold text-gray-500 leading-relaxed">
            This service is not a substitute for professional mental health care.
            If you are experiencing a mental health crisis, please contact the
            988 Suicide & Crisis Lifeline (call or text 988) or the SAMHSA
            National Helpline (1-800-662-4357). These services are free,
            confidential, and available 24/7.
          </p>
        </section>

        <section className="mb-5">
          <h2 className="mb-2 text-[11px] font-black text-gray-800 uppercase tracking-[0.15em]">
            Limitation of Liability
          </h2>
          <p className="text-[11px] font-bold text-gray-500 leading-relaxed">
            This service is provided &ldquo;as is&rdquo; without warranties of
            any kind, express or implied. We are not liable for any damages
            arising from your use of the service, including but not limited to
            direct, indirect, incidental, or consequential damages.
          </p>
        </section>

        <section className="mb-5">
          <h2 className="mb-2 text-[11px] font-black text-gray-800 uppercase tracking-[0.15em]">
            Changes to Terms
          </h2>
          <p className="text-[11px] font-bold text-gray-500 leading-relaxed">
            We may update these terms from time to time. When we do, we will
            update the version number and date above. Significant changes may
            require you to re-accept the updated terms. Your consent records
            include the version of terms you accepted.
          </p>
        </section>

        <div className="mt-8 rounded-xl bg-gray-50 border border-gray-200 p-3 text-[10px] font-bold text-gray-400">
          <p>
            <strong>Note:</strong> These terms of service are a placeholder for
            legal review. Please consult with a legal professional before public
            launch.
          </p>
        </div>
      </article>
    </div>
  );
}
