import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
};

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-white py-12 px-4">
      <article className="mx-auto max-w-2xl text-charcoal">
        <h1 className="mb-2 text-3xl font-semibold">Terms of Service</h1>
        <p className="mb-8 text-sm text-charcoal/50">
          Version 1.0 &mdash; Last updated: February 21, 2026
        </p>

        <section className="mb-8">
          <h2 className="mb-3 text-xl font-semibold">Service Description</h2>
          <p className="leading-relaxed">
            This service provides AI-guided wellness and relaxation experiences.
            It is designed for adult relaxation and well-being purposes only.
            This service is <strong>not</strong> a therapy service, medical
            service, or substitute for professional mental health care.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="mb-3 text-xl font-semibold">Eligibility</h2>
          <p className="leading-relaxed">
            You must be 18 years of age or older to use this service. By
            creating an account and completing age verification, you confirm that
            you meet this eligibility requirement.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="mb-3 text-xl font-semibold">AI Disclosure</h2>
          <p className="leading-relaxed">
            All guidance provided through this service is generated by
            artificial intelligence. You are interacting with an AI system, not a
            human therapist, counselor, or healthcare provider. The AI-generated
            content is for wellness and relaxation purposes only.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="mb-3 text-xl font-semibold">Acceptable Use</h2>
          <p className="mb-2 leading-relaxed">
            This service is intended for wellness and relaxation use only. You
            agree not to:
          </p>
          <ul className="ml-6 list-disc space-y-1 leading-relaxed">
            <li>Use the service for any illegal purpose</li>
            <li>
              Attempt to generate content outside the scope of wellness and
              relaxation
            </li>
            <li>Misrepresent your age or identity</li>
            <li>
              Share, record, or redistribute session content without
              authorization
            </li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="mb-3 text-xl font-semibold">Content Disclaimer</h2>
          <p className="leading-relaxed">
            This service is not a substitute for professional mental health care.
            If you are experiencing a mental health crisis, please contact the
            988 Suicide & Crisis Lifeline (call or text 988) or the SAMHSA
            National Helpline (1-800-662-4357). These services are free,
            confidential, and available 24/7.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="mb-3 text-xl font-semibold">
            Limitation of Liability
          </h2>
          <p className="leading-relaxed">
            This service is provided &ldquo;as is&rdquo; without warranties of
            any kind, express or implied. We are not liable for any damages
            arising from your use of the service, including but not limited to
            direct, indirect, incidental, or consequential damages.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="mb-3 text-xl font-semibold">Changes to Terms</h2>
          <p className="leading-relaxed">
            We may update these terms from time to time. When we do, we will
            update the version number and date above. Significant changes may
            require you to re-accept the updated terms. Your consent records
            include the version of terms you accepted.
          </p>
        </section>

        <div className="mt-12 rounded-lg bg-cream p-4 text-sm text-charcoal/60">
          <p>
            <strong>Note:</strong> These terms of service are a placeholder for
            legal review. Please consult with a legal professional before public
            launch.
          </p>
        </div>
      </article>
    </div>
  );
}
